sudo: false
language: node_js
node_js:
  - 4
  - 6

cache: 'yarn'

notifications:
  email: false

before_install:
  - .travis/before_install.sh

script:
  - npm run lint
  - npm run dist
  - npm run coverage:ci
  - npm run it

after_success:
  - .travis/after_success.sh

git:
  depth: 1
