node8Environment: &node8Environment
  docker:
    - image: circleci/node:8@sha256:b9a9cba0060fee04631ec513f12d4546729e024ce7a2b9d80c104c48bd4cb006
  working_directory: ~/nodejs
node10Environment: &node10Environment
  docker:
    - image: circleci/node:10
  working_directory: ~/nodejs

aliases:
  - &restore_yarn_cache
    keys:
      - v2-yarn-cache-{{ checksum "yarn.lock" }}

  - &save_yarn_cache
    key: v2-yarn-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - ~/.cache/yarn

  - &yarn_install
    name: Installing
    command: yarn install --pure-lockfile

  - &unit_test
    name: Unit testing
    # Limiting the workers of Jest to 10
    # as the build otherwise dies due to resouce restrictions.
    command: yarn test:ci --maxWorkers=10

  - &unit_test_with_coverage
    name: Unit testing (with coverage report)
    command: yarn test:coverage:ci

version: 2
jobs:
  lint:
    <<: *node10Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run: *yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Linting
          # Limiting the workers of Jest to 10
          # as the build otherwise dies due to resouce restrictions.
          command: yarn lint --maxWorkers=10
  test_unit_node_8:
    <<: *node8Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run: *yarn_install
      - save_cache: *save_yarn_cache
      - run: *unit_test
  test_unit_node_10:
    <<: *node10Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run: *yarn_install
      - save_cache: *save_yarn_cache
      - run: *unit_test_with_coverage
  test_integration:
    <<: *node10Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run: *yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Integration testing
          command: yarn test:integration
  build_aws_lambda_layer:
    <<: *node8Environment
    steps:
      - checkout
      - run: sh scripts/build-aws-lambda-layer
      - store_artifacts:
          path: dist/commercetools-nodejs-sdk.zip
          destination: commercetools-nodejs-sdk.zip
      - persist_to_workspace:
          root: /home/circleci/nodejs
          paths:
            - dist
  publish_aws_lambda_layer:
    docker:
      - image: mesosphere/aws-cli
    working_directory: ~/nodejs
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/nodejs
      - run: sh scripts/publish-aws-lambda-layer

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test_unit_node_8:
          requires:
            - lint
      - test_unit_node_10:
          requires:
            - lint
      - build_aws_lambda_layer:
          requires:
            - test_unit_node_8
      - publish_aws_lambda_layer:
          requires:
            - build_aws_lambda_layer
      - test_integration:
          context: org-global
          requires:
            # Only depending on one unit testing
            # job will speed up the build by starting
            # the integration testing early (in confidence).
            - test_unit_node_10
